### ISSUE TITLE
i18n review checklist for baggage

### ISSUE THREAD

**Issue by kalyanaj** [w3c/baggage#93]
Short i18n review checklist is [here](https://www.w3.org/International/i18n-drafts/techniques/shortchecklist.html)

1. [ ] _If the spec (or its implementation) contains any natural language text that will be read by a human (this includes error messages or other UI text, JSON strings, etc, etc),_

    The baggage spec doesn't contain any natural language text that will be read by a human.
    
2. [ ] _If the spec (or its implementation) allows content authors to produce typographically appealing text, either in its own right, or in association with graphics._

    N/A for Baggage spec.

3. [ ] _If the spec (or its implementation) allows the user to point into text, creates text fragments, concatenates text, allows the user to select or step through text (using a cursor or other methods), etc._

     N/A for Baggage spec.

4. [ ] _If the spec (or its implementation) allows searching or matching of text, including syntax and identifiers_

    N/A for Baggage spec.

5. [ ] _If the spec (or its implementation) sorts text_

    N/A for Baggage spec.

6. [ ] _If the spec (or its implementation) captures user input_

    N/A for Baggage spec.

7. [ ] _If the spec (or its implementation) deals with time in any way that will be read by humans and/or crosses time zone boundaries_

    N/A for Baggage spec.

8. [ ] _If the spec (or its implementation) allows any character encoding other than UTF-8._

    N/A for Baggage spec.

9. [ ] _If the spec (or its implementation) defines markup._

    N/A for Baggage spec.

10. [ ] _If the spec (or its implementation) deals with names, addresses, time & date formats, etc_

    N/A for Baggage spec.

11. [ ] _If the spec (or its implementation) describes a format or data that is likely to need localization._

    N/A for Baggage spec.

12. [ ] _If the spec (or its implementation) makes any reference to or relies on any cultural norms_

    TODO: N/A for baggage spec. When we did the TAG review, there was a question about the name of the spec "Baggage" and whether it relies on any cultural norms, the TAG team was satisfied with the answer we gave: https://github.com/w3c/baggage/issues/83

**Comment by aphillips** [comment]
I have updated your review request and set a target date of 2022-05-27. Please let me know if you need the I18N WG review sooner than this.

**Comment by kalyanaj** [comment]
Thanks @aphillips for the update and for the above target date - that sounds good.

**Comment by kalyanaj** [comment]
Closing this issue as the review has been completed and issues have been filed for the follow-up items.
